# Generated by Django 5.0.4 on 2024-06-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_club_tag'),
        ('Member', '0002_alter_joinrequest_club_and_more'),
        ('authentication', '0005_alter_student_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberJoined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
            options={
                'unique_together': {('student', 'club')},
            },
        ),
    ]
