# Generated by Django 5.0.4 on 2024-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('general_user', 'General User')], max_length=100, null=True),
        ),
    ]
