# Generated by Django 5.0.4 on 2024-07-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_memberjoined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_request', models.IntegerField(default=0)),
                ('event', models.IntegerField(default=0)),
            ],
        ),
    ]
