# Generated by Django 5.0.4 on 2024-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_notification_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('general_user', 'General User')], default='general_user', max_length=100, null=True),
        ),
    ]
