# Generated by Django 5.0.4 on 2024-08-02 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_alter_notification_user_type'),
        ('authentication', '0005_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student', verbose_name='Students'),
        ),
    ]
