# Generated by Django 5.0.4 on 2024-08-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_notification_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.memberjoined', verbose_name='Students'),
        ),
    ]
