# Generated by Django 5.0.4 on 2024-08-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0008_alter_notification_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='All_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.memberjoined'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ManyToManyField(related_name='Students', to='Member.memberjoined', verbose_name='Students'),
        ),
    ]
