# Generated by Django 5.0.4 on 2024-08-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0009_notification_all_members_alter_notification_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
    ]
