# Generated by Django 5.0.4 on 2024-08-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0010_remove_notification_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='All_members',
            new_name='Student',
        ),
    ]
