# Generated by Django 5.1 on 2024-11-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_notice_created_at'),
        ('Member', '0013_remove_notification_total_alter_notification_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.notice'),
        ),
    ]
