# Generated by Django 5.0.4 on 2024-06-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='tag',
            field=models.CharField(default='club', max_length=10, unique=True),
        ),
    ]
