# Generated by Django 5.1 on 2024-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_notice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
