# Generated by Django 5.1 on 2024-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='event_image1',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image2',
            field=models.ImageField(blank=True, default='profile_pic/new_logo.png', upload_to='event_image'),
        ),
    ]
